[package]
name = "midi314-display"
version = "0.1.0"
authors = ["Guillaume Savaton <guillaume@baierouge.fr>"]

[dependencies]
jack = "0.6"
midi314 = { path = "../midi314" }
pcd8544 = { path = "../pcd8544" }
